### ISSUE TITLE
Make the site Mobile responsive.

### ISSUE THREAD

**Issue by stephin007** [stephin007/lorem-ipsum#4]
Developer can use any type of framework to make it responsive.

**Comment by aman909909** [comment]
Hey.
Can I pick this issue?

**Comment by stephin007** [comment]
Yes @aman909909 , Please do create a new branch from the main master branch and then start working.

_P.S. Your branch will be auto deployed to staging as well_

**Comment by aman909909** [comment]
I have created a PR. Please review it.

**Comment by stephin007** [comment]
Left Few comments @aman909909  ! Please fix that , as well :)
