### ISSUE TITLE
Add Dark Mode

### ISSUE THREAD

**Issue by stephin007** [stephin007/lorem-ipsum#7]
> ## **Add a Togglable Switch to Dark And Light mode.**

Points to noted:
 - Its default should always be in DARK.
 - If the current mode is Dark , it should not switch if we refresh the browser, it should maintain its state

**Comment by Justinnn07** [comment]
hey, i would like to contribute!

**Comment by stephin007** [comment]
Sure @Justinnn07 , please do!

**Comment by stephin007** [comment]
This issue is fixed in  : https://github.com/stephin007/lorem-ipsum/pull/18
